// <auto-generated />
namespace ElectronicSchem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GlobalUpdate4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GlobalUpdate4));
        
        string IMigrationMetadata.Id
        {
            get { return "201606271801509_GlobalUpdate4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
